name: release
on:
  schedule:
    - cron: "10 10 1-31/2 * *"
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out project files
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check and release
        run: |
          sudo apt-get install -y p7zip-full
          repos="2dust/v2rayN"
          v2rayN_latest_version=$(curl \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" \
          -s "https://api.github.com/repos/$repos/tags" \
          --connect-timeout 10 | grep  -m1 "name" | cut -d\" -f4)
          echo $v2rayN_latest_version
          
          DIST_TAGS_URL="https://api.github.com/repos/${{ github.repository }}/tags"
          DIST_TAG_FOUND=`curl -H "Accept: application/vnd.github.v3+json" -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" -s ${DIST_TAGS_URL} --connect-timeout 5 | grep "\"name\"\: \"${v2rayN_latest_version}\""` || true

          
          if [ -z ${DIST_TAG_FOUND} ]; then
            rm -rf *

            wget https://github.com/$repos/releases/download/$v2rayN_latest_version/v2rayN.zip
            unzip v2rayN.zip
            mkdir tmp


            repos="v2fly/v2ray-core"
            latest_version=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" \
            -s "https://api.github.com/repos/$repos/tags" \
            --connect-timeout 10 | grep  -m1 "name" | cut -d\" -f4)
            echo $latest_version
            wget https://github.com/$repos/releases/download/$latest_version/v2ray-windows-64.zip
            unzip v2ray-windows-64.zip -d ./tmp
            
            
            repos="XTLS/Xray-core"
            latest_version=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36" \
            -s "https://api.github.com/repos/$repos/tags" \
            --connect-timeout 10 | grep  -m1 "name" | cut -d\" -f4)
            echo $latest_version
            wget https://github.com/$repos/releases/download/$latest_version/Xray-windows-64.zip
            unzip Xray-windows-64.zip -od ./tmp
            
            cp -rf ./tmp/* ./v2rayN/
            rm *.zip tmp -fr

            7z a -t7z ./v2rayN-${latest_version}.7z ./v2rayN
            cp ./v2rayN-${latest_version}.7z ./v2rayN.7z
            sha256sum ./v2rayN.7z > sha256sum.txt
            
            git add .
            git config user.name "Scaleya"
            git config user.email "61817665+Scaleya@users.noreply.github.com"
            git commit -m "Version ${v2rayN_latest_version}"
            git tag -a "${v2rayN_latest_version}" -m "Version ${v2rayN_latest_version}"
            git remote add release "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
            git push -u --follow-tags release main
          fi
